FROM jenkins/jenkins:lts
USER root
RUN apt-get update
RUN apt-get install -y python3-pip
ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
COPY ./pyproject.toml .
RUN poetry install --no-dev
