version: "3"
services:
  jenkins:
    image: pyjenkins
    container_name: "jenkins_python"
    ports:
      - "6060:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "./exchange:/exchange"
